[package]
name = "rust_2019_15"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.49.2"
intcode_rust = { version = "0.1.0", path = "../intcode_rust" }
relative-path = "1.9.2"
