[package]
name = "rust_2019_12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.1"
regex = "1.10.3"
relative-path = "1.9.2"
